version: '3'

services:
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - ${DATA_PATH_HOST}/grafana:/var/lib/grafana
    restart: always
  influx-db:
    build:
      context: .
      dockerfile: dockers/Db.Dockerfile
    environment:
      - INFLUXDB_DB=${INFLUXDB_DB}
      - INFLUXDB_USER=${INFLUXDB_USER}
      - INFLUXDB_USER_PASSWORD=${INFLUXDB_USER_PASSWORD}
      - TZ=${TIMEZONE}
    volumes:
      - ${DATA_PATH_HOST}/influxdb:/var/lib/influxdb
      # - dockers/influxdb.conf:/etc/influxdb/influxdb.conf:ro
    ports:
      - "${DB_PORT}:8086"
    # restart: always
  api:
    build:
      context: .
      dockerfile: dockers/Dockerfile
    ports:
      - "${PUBLIC_PORT}:80"
    # restart: always